Repository sysc3010-t3/server, pull requests merged in 2019-12, with the labels that each got.

#17 Implement multi-threaded database connection
  dbSchema.sql
  handlers.py
  main.py
  server.py
  utils.py
Labels: enhancement

#22 Update LINK handler with new design changes and ERROR cases
  handlers.py
Labels: bug, enhancement

#23 Update GET_CARS handler to include "is_on" field
  handlers.py
Labels: enhancement

#25 Add a README
  README.md
Labels: documentation

#24 Replace print statements with logging
  handlers.py
  main.py
  server.py
Labels: enhancement
